# Generated by Django 5.1.6 on 2025-04-08 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Unique name identifier for the product', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(choices=[('PERFUME', 'PERFUME'), ('EAU DE PERFUM', 'EAU DE PERFUM'), ('EAU DE TOILETTE', 'EAU DE TOILETTE'), ('EAU DE COLOGNE', 'EAU DE COLOGNE'), ('EAU FRAICHE', 'EAU FRAICHE'), ('AFTERSHAVE', 'AFTERSHAVE'), ('Mist', 'Mist')], db_index=True, max_length=255, null=True)),
                ('volume', models.IntegerField(default=0, help_text='ml.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('package', models.CharField(choices=[('No Package', 'No Package'), ('Simple', 'Simple'), ('Luxury', 'Luxury')], max_length=255, null=True)),
                ('top_note', models.CharField(choices=[('Aromatic', 'Aromatic'), ('Mediterranean', 'Mediterranean'), ('Citrus', 'Citrus'), ('Fruity', 'Fruity'), ('Floral', 'Floral'), ('Oriental', 'Oriental'), ('Woody', 'Woody'), ('Fresh', 'Fresh'), ('Spicy', 'Spicy'), ('Aquatic', 'Aquatic'), ('Leather', 'Leather')], max_length=255, null=True)),
                ('middle_note', models.CharField(choices=[('Aromatic', 'Aromatic'), ('Mediterranean', 'Mediterranean'), ('Citrus', 'Citrus'), ('Fruity', 'Fruity'), ('Floral', 'Floral'), ('Oriental', 'Oriental'), ('Woody', 'Woody'), ('Fresh', 'Fresh'), ('Spicy', 'Spicy'), ('Aquatic', 'Aquatic'), ('Leather', 'Leather')], max_length=255, null=True)),
                ('base_note', models.CharField(choices=[('Aromatic', 'Aromatic'), ('Mediterranean', 'Mediterranean'), ('Citrus', 'Citrus'), ('Fruity', 'Fruity'), ('Floral', 'Floral'), ('Oriental', 'Oriental'), ('Woody', 'Woody'), ('Fresh', 'Fresh'), ('Spicy', 'Spicy'), ('Aquatic', 'Aquatic'), ('Leather', 'Leather')], max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unisex', 'unisex')], db_index=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether this product is available for purchase')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'abstract': False,
            },
        ),
    ]
